// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/CatConspiracy.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CatConspiracyInfo {

  /// <summary>Holder for reflection information generated from proto/CatConspiracy.proto</summary>
  public static partial class CatConspiracyReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/CatConspiracy.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CatConspiracyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chlwcm90by9DYXRDb25zcGlyYWN5LnByb3RvEhFDYXRDb25zcGlyYWN5SW5m",
            "byLLAQoRQ2F0Q29uc3BpcmFjeUluZm8SUgoScmVzdWx0RXZlbnRfY29uZmln",
            "GAEgAygLMjYuQ2F0Q29uc3BpcmFjeUluZm8uQ2F0Q29uc3BpcmFjeUluZm8u",
            "Q2F0Q29uc3BpcmFjeUl0ZW0aYgoRQ2F0Q29uc3BpcmFjeUl0ZW0SFAoMQ29u",
            "c3BpcmFjeUlkGAEgASgDEhMKC2Rlc2NyaXB0aW9uGAIgASgJEhEKCWNvbmRp",
            "dGlvbhgDIAEoAxIPCgdHcm91cElkGAQgASgDYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CatConspiracyInfo.CatConspiracyInfo), global::CatConspiracyInfo.CatConspiracyInfo.Parser, new[]{ "ResultEventConfig" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::CatConspiracyInfo.CatConspiracyInfo.Types.CatConspiracyItem), global::CatConspiracyInfo.CatConspiracyInfo.Types.CatConspiracyItem.Parser, new[]{ "ConspiracyId", "Description", "Condition", "GroupId" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// @wrapper 猫咪阴谋配置表(CatConspiracyInfo.pb.json)
  /// </summary>
  public sealed partial class CatConspiracyInfo : pb::IMessage<CatConspiracyInfo> {
    private static readonly pb::MessageParser<CatConspiracyInfo> _parser = new pb::MessageParser<CatConspiracyInfo>(() => new CatConspiracyInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CatConspiracyInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CatConspiracyInfo.CatConspiracyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CatConspiracyInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CatConspiracyInfo(CatConspiracyInfo other) : this() {
      resultEventConfig_ = other.resultEventConfig_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CatConspiracyInfo Clone() {
      return new CatConspiracyInfo(this);
    }

    /// <summary>Field number for the "resultEvent_config" field.</summary>
    public const int ResultEventConfigFieldNumber = 1;
    private static readonly pb::FieldCodec<global::CatConspiracyInfo.CatConspiracyInfo.Types.CatConspiracyItem> _repeated_resultEventConfig_codec
        = pb::FieldCodec.ForMessage(10, global::CatConspiracyInfo.CatConspiracyInfo.Types.CatConspiracyItem.Parser);
    private readonly pbc::RepeatedField<global::CatConspiracyInfo.CatConspiracyInfo.Types.CatConspiracyItem> resultEventConfig_ = new pbc::RepeatedField<global::CatConspiracyInfo.CatConspiracyInfo.Types.CatConspiracyItem>();
    /// <summary>
    /// @name 猫咪阴谋配置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CatConspiracyInfo.CatConspiracyInfo.Types.CatConspiracyItem> ResultEventConfig {
      get { return resultEventConfig_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CatConspiracyInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CatConspiracyInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!resultEventConfig_.Equals(other.resultEventConfig_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= resultEventConfig_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      resultEventConfig_.WriteTo(output, _repeated_resultEventConfig_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += resultEventConfig_.CalculateSize(_repeated_resultEventConfig_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CatConspiracyInfo other) {
      if (other == null) {
        return;
      }
      resultEventConfig_.Add(other.resultEventConfig_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            resultEventConfig_.AddEntriesFrom(input, _repeated_resultEventConfig_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the CatConspiracyInfo message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class CatConspiracyItem : pb::IMessage<CatConspiracyItem> {
        private static readonly pb::MessageParser<CatConspiracyItem> _parser = new pb::MessageParser<CatConspiracyItem>(() => new CatConspiracyItem());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<CatConspiracyItem> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::CatConspiracyInfo.CatConspiracyInfo.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CatConspiracyItem() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CatConspiracyItem(CatConspiracyItem other) : this() {
          conspiracyId_ = other.conspiracyId_;
          description_ = other.description_;
          condition_ = other.condition_;
          groupId_ = other.groupId_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CatConspiracyItem Clone() {
          return new CatConspiracyItem(this);
        }

        /// <summary>Field number for the "ConspiracyId" field.</summary>
        public const int ConspiracyIdFieldNumber = 1;
        private long conspiracyId_;
        /// <summary>
        /// @name 阴谋编号
        /// @key
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public long ConspiracyId {
          get { return conspiracyId_; }
          set {
            conspiracyId_ = value;
          }
        }

        /// <summary>Field number for the "description" field.</summary>
        public const int DescriptionFieldNumber = 2;
        private string description_ = "";
        /// <summary>
        /// @name 阴谋描述
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Description {
          get { return description_; }
          set {
            description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "condition" field.</summary>
        public const int ConditionFieldNumber = 3;
        private long condition_;
        /// <summary>
        /// @name 达成条件
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public long Condition {
          get { return condition_; }
          set {
            condition_ = value;
          }
        }

        /// <summary>Field number for the "GroupId" field.</summary>
        public const int GroupIdFieldNumber = 4;
        private long groupId_;
        /// <summary>
        /// @name 阴谋组编号
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public long GroupId {
          get { return groupId_; }
          set {
            groupId_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as CatConspiracyItem);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(CatConspiracyItem other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ConspiracyId != other.ConspiracyId) return false;
          if (Description != other.Description) return false;
          if (Condition != other.Condition) return false;
          if (GroupId != other.GroupId) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (ConspiracyId != 0L) hash ^= ConspiracyId.GetHashCode();
          if (Description.Length != 0) hash ^= Description.GetHashCode();
          if (Condition != 0L) hash ^= Condition.GetHashCode();
          if (GroupId != 0L) hash ^= GroupId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (ConspiracyId != 0L) {
            output.WriteRawTag(8);
            output.WriteInt64(ConspiracyId);
          }
          if (Description.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Description);
          }
          if (Condition != 0L) {
            output.WriteRawTag(24);
            output.WriteInt64(Condition);
          }
          if (GroupId != 0L) {
            output.WriteRawTag(32);
            output.WriteInt64(GroupId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (ConspiracyId != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(ConspiracyId);
          }
          if (Description.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
          }
          if (Condition != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(Condition);
          }
          if (GroupId != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(GroupId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(CatConspiracyItem other) {
          if (other == null) {
            return;
          }
          if (other.ConspiracyId != 0L) {
            ConspiracyId = other.ConspiracyId;
          }
          if (other.Description.Length != 0) {
            Description = other.Description;
          }
          if (other.Condition != 0L) {
            Condition = other.Condition;
          }
          if (other.GroupId != 0L) {
            GroupId = other.GroupId;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                ConspiracyId = input.ReadInt64();
                break;
              }
              case 18: {
                Description = input.ReadString();
                break;
              }
              case 24: {
                Condition = input.ReadInt64();
                break;
              }
              case 32: {
                GroupId = input.ReadInt64();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
