// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/TotalConspiracy.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TotalConspiracy {

  /// <summary>Holder for reflection information generated from proto/TotalConspiracy.proto</summary>
  public static partial class TotalConspiracyReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/TotalConspiracy.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TotalConspiracyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chtwcm90by9Ub3RhbENvbnNwaXJhY3kucHJvdG8SD1RvdGFsQ29uc3BpcmFj",
            "eSLSAQoPVG90YWxDb25zcGlyYWN5ElAKEnJlc3VsdEV2ZW50X2NvbmZpZxgB",
            "IAMoCzI0LlRvdGFsQ29uc3BpcmFjeS5Ub3RhbENvbnNwaXJhY3kuVG90YWxD",
            "b25zcGlyYWN5SXRlbRptChNUb3RhbENvbnNwaXJhY3lJdGVtEg8KB0dyb3Vw",
            "SWQYASABKAMSFAoMQ29uc3BpcmFjeUlkGAIgAygFEhcKD0NvbnNwaXJhY3lU",
            "aXRsZRgDIAEoCRIWCg5Db25zcGlyYWN5RGVzYxgEIAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TotalConspiracy.TotalConspiracy), global::TotalConspiracy.TotalConspiracy.Parser, new[]{ "ResultEventConfig" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::TotalConspiracy.TotalConspiracy.Types.TotalConspiracyItem), global::TotalConspiracy.TotalConspiracy.Types.TotalConspiracyItem.Parser, new[]{ "GroupId", "ConspiracyId", "ConspiracyTitle", "ConspiracyDesc" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// @wrapper 阴谋总表(TotalConspiracy.pb.json)
  /// </summary>
  public sealed partial class TotalConspiracy : pb::IMessage<TotalConspiracy> {
    private static readonly pb::MessageParser<TotalConspiracy> _parser = new pb::MessageParser<TotalConspiracy>(() => new TotalConspiracy());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TotalConspiracy> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TotalConspiracy.TotalConspiracyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TotalConspiracy() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TotalConspiracy(TotalConspiracy other) : this() {
      resultEventConfig_ = other.resultEventConfig_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TotalConspiracy Clone() {
      return new TotalConspiracy(this);
    }

    /// <summary>Field number for the "resultEvent_config" field.</summary>
    public const int ResultEventConfigFieldNumber = 1;
    private static readonly pb::FieldCodec<global::TotalConspiracy.TotalConspiracy.Types.TotalConspiracyItem> _repeated_resultEventConfig_codec
        = pb::FieldCodec.ForMessage(10, global::TotalConspiracy.TotalConspiracy.Types.TotalConspiracyItem.Parser);
    private readonly pbc::RepeatedField<global::TotalConspiracy.TotalConspiracy.Types.TotalConspiracyItem> resultEventConfig_ = new pbc::RepeatedField<global::TotalConspiracy.TotalConspiracy.Types.TotalConspiracyItem>();
    /// <summary>
    /// @name 阴谋总表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::TotalConspiracy.TotalConspiracy.Types.TotalConspiracyItem> ResultEventConfig {
      get { return resultEventConfig_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TotalConspiracy);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TotalConspiracy other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!resultEventConfig_.Equals(other.resultEventConfig_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= resultEventConfig_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      resultEventConfig_.WriteTo(output, _repeated_resultEventConfig_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += resultEventConfig_.CalculateSize(_repeated_resultEventConfig_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TotalConspiracy other) {
      if (other == null) {
        return;
      }
      resultEventConfig_.Add(other.resultEventConfig_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            resultEventConfig_.AddEntriesFrom(input, _repeated_resultEventConfig_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the TotalConspiracy message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class TotalConspiracyItem : pb::IMessage<TotalConspiracyItem> {
        private static readonly pb::MessageParser<TotalConspiracyItem> _parser = new pb::MessageParser<TotalConspiracyItem>(() => new TotalConspiracyItem());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<TotalConspiracyItem> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::TotalConspiracy.TotalConspiracy.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public TotalConspiracyItem() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public TotalConspiracyItem(TotalConspiracyItem other) : this() {
          groupId_ = other.groupId_;
          conspiracyId_ = other.conspiracyId_.Clone();
          conspiracyTitle_ = other.conspiracyTitle_;
          conspiracyDesc_ = other.conspiracyDesc_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public TotalConspiracyItem Clone() {
          return new TotalConspiracyItem(this);
        }

        /// <summary>Field number for the "GroupId" field.</summary>
        public const int GroupIdFieldNumber = 1;
        private long groupId_;
        /// <summary>
        /// @name 阴谋组编号
        /// @key
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public long GroupId {
          get { return groupId_; }
          set {
            groupId_ = value;
          }
        }

        /// <summary>Field number for the "ConspiracyId" field.</summary>
        public const int ConspiracyIdFieldNumber = 2;
        private static readonly pb::FieldCodec<int> _repeated_conspiracyId_codec
            = pb::FieldCodec.ForInt32(18);
        private readonly pbc::RepeatedField<int> conspiracyId_ = new pbc::RepeatedField<int>();
        /// <summary>
        /// @name 目标编号
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<int> ConspiracyId {
          get { return conspiracyId_; }
        }

        /// <summary>Field number for the "ConspiracyTitle" field.</summary>
        public const int ConspiracyTitleFieldNumber = 3;
        private string conspiracyTitle_ = "";
        /// <summary>
        /// @name 阴谋标题
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string ConspiracyTitle {
          get { return conspiracyTitle_; }
          set {
            conspiracyTitle_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "ConspiracyDesc" field.</summary>
        public const int ConspiracyDescFieldNumber = 4;
        private string conspiracyDesc_ = "";
        /// <summary>
        /// @name 阴谋描述
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string ConspiracyDesc {
          get { return conspiracyDesc_; }
          set {
            conspiracyDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as TotalConspiracyItem);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(TotalConspiracyItem other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (GroupId != other.GroupId) return false;
          if(!conspiracyId_.Equals(other.conspiracyId_)) return false;
          if (ConspiracyTitle != other.ConspiracyTitle) return false;
          if (ConspiracyDesc != other.ConspiracyDesc) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (GroupId != 0L) hash ^= GroupId.GetHashCode();
          hash ^= conspiracyId_.GetHashCode();
          if (ConspiracyTitle.Length != 0) hash ^= ConspiracyTitle.GetHashCode();
          if (ConspiracyDesc.Length != 0) hash ^= ConspiracyDesc.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (GroupId != 0L) {
            output.WriteRawTag(8);
            output.WriteInt64(GroupId);
          }
          conspiracyId_.WriteTo(output, _repeated_conspiracyId_codec);
          if (ConspiracyTitle.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(ConspiracyTitle);
          }
          if (ConspiracyDesc.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(ConspiracyDesc);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (GroupId != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(GroupId);
          }
          size += conspiracyId_.CalculateSize(_repeated_conspiracyId_codec);
          if (ConspiracyTitle.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ConspiracyTitle);
          }
          if (ConspiracyDesc.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ConspiracyDesc);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(TotalConspiracyItem other) {
          if (other == null) {
            return;
          }
          if (other.GroupId != 0L) {
            GroupId = other.GroupId;
          }
          conspiracyId_.Add(other.conspiracyId_);
          if (other.ConspiracyTitle.Length != 0) {
            ConspiracyTitle = other.ConspiracyTitle;
          }
          if (other.ConspiracyDesc.Length != 0) {
            ConspiracyDesc = other.ConspiracyDesc;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                GroupId = input.ReadInt64();
                break;
              }
              case 18:
              case 16: {
                conspiracyId_.AddEntriesFrom(input, _repeated_conspiracyId_codec);
                break;
              }
              case 26: {
                ConspiracyTitle = input.ReadString();
                break;
              }
              case 34: {
                ConspiracyDesc = input.ReadString();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
